acuerdo:
    path:     /
    defaults: { _controller: "AcuerdosGestionBundle:Acuerdo:index" }

acuerdo_show:
    path:     /{id}/show
    defaults: { _controller: "AcuerdosGestionBundle:Acuerdo:show" }

acuerdo_new:
    path:     /new
    defaults: { _controller: "AcuerdosGestionBundle:Acuerdo:new" }

acuerdo_create:
    path:     /create
    defaults: { _controller: "AcuerdosGestionBundle:Acuerdo:create" }
    methods:  POST

acuerdo_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcuerdosGestionBundle:Acuerdo:edit" }

acuerdo_update:
    path:     /{id}/update
    defaults: { _controller: "AcuerdosGestionBundle:Acuerdo:update" }
    methods:  [POST, PUT]

acuerdo_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcuerdosGestionBundle:Acuerdo:delete" }
#    methods:  [POST, DELETE]
