area:
    path:     /
    defaults: { _controller: "AcuerdosGestionBundle:Area:index" }

#area_show:
#    path:     /{id}/show
#    defaults: { _controller: "AcuerdosGestionBundle:Area:show" }

area_new:
    path:     /new
    defaults: { _controller: "AcuerdosGestionBundle:Area:new" }

area_create:
    path:     /create
    defaults: { _controller: "AcuerdosGestionBundle:Area:create" }
    methods:  POST

area_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcuerdosGestionBundle:Area:edit" }

area_update:
    path:     /{id}/update
    defaults: { _controller: "AcuerdosGestionBundle:Area:update" }
    methods:  [POST, PUT]

area_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcuerdosGestionBundle:Area:delete" }
#    methods:  [POST, DELETE]
