persona:
    path:     /
    defaults: { _controller: "AcuerdosGestionBundle:Persona:index" }

persona_show:
    path:     /{id}/show
    defaults: { _controller: "AcuerdosGestionBundle:Persona:show" }

persona_new:
    path:     /new
    defaults: { _controller: "AcuerdosGestionBundle:Persona:new" }

persona_create:
    path:     /create
    defaults: { _controller: "AcuerdosGestionBundle:Persona:create" }
    methods:  POST

persona_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcuerdosGestionBundle:Persona:edit" }

persona_update:
    path:     /{id}/update
    defaults: { _controller: "AcuerdosGestionBundle:Persona:update" }
    methods:  [POST, PUT]

persona_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcuerdosGestionBundle:Persona:delete" }

ajax_person_create:
    path:     /add/persona
    defaults: { _controller: "AcuerdosGestionBundle:Persona:agregarPersona" }

change_password:
    path:     /change_password/{id}
    defaults: { _controller: "AcuerdosGestionBundle:Persona:changePassword" }

#ajax_search_person:
#    path:     /search/persona
#    defaults: { _controller: "AcuerdosGestionBundle:Persona:searchPersona" }
