<?php

namespace Acuerdos\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReunionPersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReunionPersonaRepository extends EntityRepository
{
}
